// [FORCE-UI] Generates lib/framework-components.ts from the docs tree.
//
// That manifest tells the framework switcher whether a component page exists
// for a base before navigating to it. It used to be hand-maintained, and had
// drifted badly: vue was missing 10 pages that exist, svelte 5, ember listed a
// scroll-area page that does not exist, and the "aria" base was absent
// altogether so switching to React Aria always bounced to /docs/components.
//
//   pnpm --filter=v4 framework-components         regenerate
//   pnpm --filter=v4 framework-components:check   fail if out of date (CI)
import { promises as fs } from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

import { BASES } from "../registry/bases.ts"

const V4_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const DOCS_DIR = path.join(V4_DIR, "content/docs/components")
const OUT_FILE = path.join(V4_DIR, "lib/framework-components.ts")

async function slugsForBase(base: string): Promise<string[]> {
  const dir = path.join(DOCS_DIR, base)
  let entries: string[]
  try {
    entries = await fs.readdir(dir)
  } catch {
    return []
  }
  return entries
    .filter((f) => f.endsWith(".mdx") && f !== "index.mdx")
    .map((f) => f.slice(0, -".mdx".length))
    .sort()
}

async function render() {
  const blocks: string[] = []

  for (const base of BASES) {
    const slugs = await slugsForBase(base.name)
    if (slugs.length === 0) {
      continue
    }
    const items = slugs.map((s) => `    "${s}",`).join("\n")
    blocks.push(`  ${base.name}: new Set([\n${items}\n  ]),`)
  }

  return `// Manifest of available component pages per base.
//
// GENERATED by scripts/build-framework-components.mts from
// content/docs/components/<base>/*.mdx. Do not edit by hand - run
// \`pnpm --filter=v4 framework-components\` after adding or removing a
// component doc page. \`framework-components:check\` guards it in CI.
//
// Used client-side by the framework switcher to decide whether a component
// page exists for a base before navigating to it.

export const FRAMEWORK_COMPONENTS: Record<string, Set<string>> = {
${blocks.join("\n")}
}

export function hasComponentForBase(
  base: string,
  componentSlug: string
): boolean {
  const components = FRAMEWORK_COMPONENTS[base]
  if (!components) return false
  if (components.has("*")) return true
  return components.has(componentSlug)
}
`
}

async function main() {
  const next = await render()
  const check = process.argv.includes("--check")
  const current = await fs.readFile(OUT_FILE, "utf-8").catch(() => "")

  if (current === next) {
    console.log("✅ lib/framework-components.ts is up to date")
    return
  }

  if (check) {
    console.error(
      "❌ lib/framework-components.ts is out of date with content/docs/components.\n" +
        "   Run: pnpm --filter=v4 framework-components"
    )
    process.exit(1)
  }

  await fs.writeFile(OUT_FILE, next, "utf-8")
  console.log(`✅ Wrote ${path.relative(V4_DIR, OUT_FILE)}`)
}

await main()
